[package]
name = "bootstrap"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "bootstrap_lib", "lexiparser", "make_lexiparser"]
default-members = ["bootstrap_lib", "lexiparser"]
resolver = "3"
