[package]
name = "make_lexiparser"
version = "0.1.0"
edition = "2024"

[dependencies]
bootstrap_lib = { git = "https://github.com/blueglyph/bootstrap", tag = "v2.0", package = "bootstrap" }
lexiparser = { git = "https://github.com/blueglyph/bootstrap", tag = "v2.0" }
