[package]
name = "lexiparser"
version = "0.1.0"
edition = "2024"

[dependencies]
# renaming "bootstrap" to avoid name confusion when this code is used in the bootstrap library
lexiparser_bootstrap = { git = "https://github.com/blueglyph/bootstrap", tag = "v2.0", package="bootstrap-lib" }
