[package]
name = "lexiparser"
version = "0.1.0"
edition = "2024"

[dependencies]
# renaming "bootstrap" to avoid name confusion when this code is used in the bootstrap library
bootstrap_lib = { git = "https://github.com/blueglyph/bootstrap", tag = "v2.2", package="bootstrap_lib" }
